/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.SanPhamDAO;
import Modal.SanPham;
import javax.swing.JOptionPane;

/**
 *
 * @author vinhn
 */
public class DiologSuaSP extends javax.swing.JDialog {

    /**
     * Creates new form DiologThemSP
     */
    int ID = 0;

    public DiologSuaSP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtChip = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtThuongHieu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHDH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMan = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tên sản phẩm");

        jTextField8.setBackground(java.awt.Color.white);

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(new java.awt.Color(22, 122, 198));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sửa sản phẩm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tên sản phẩm");

        txtTenSP.setBackground(java.awt.Color.white);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Chip xử lý");

        txtChip.setBackground(java.awt.Color.white);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Thương hiệu");

        txtThuongHieu.setBackground(java.awt.Color.white);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Dung lượng pin");

        txtPin.setBackground(java.awt.Color.white);

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Hệ điều hành");

        txtHDH.setBackground(java.awt.Color.white);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Xuất xứ");

        txtXuatXu.setBackground(java.awt.Color.white);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kích thước màn");

        txtMan.setBackground(java.awt.Color.white);

        btnSua.setBackground(new java.awt.Color(51, 153, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSua.setForeground(java.awt.Color.white);
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        txtGiaNhap.setBackground(java.awt.Color.white);

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Giá nhập");

        txtGiaBan.setBackground(java.awt.Color.white);

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Giá xuất");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtChip, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtMan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtChip, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHDH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(btnSua)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (txtChip.getText().trim().isEmpty()
                || txtGiaNhap.getText().trim().isEmpty()
                || txtGiaBan.getText().trim().isEmpty()
                || txtGiaBan.getText().trim().isEmpty()
                || txtHDH.getText().trim().isEmpty()
                || txtMan.getText().trim().isEmpty()
                || txtPin.getText().trim().isEmpty()
                || txtTenSP.getText().trim().isEmpty()
                || txtThuongHieu.getText().trim().isEmpty()
                || txtXuatXu.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!", "Thiếu thông tin", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean isOK = true;
            SanPham sp = new SanPham();
            sp.setMaSP(ID);
            sp.setTenSP(txtTenSP.getText().trim());
            sp.setSoLuong(0);
            sp.setThuongHieu(txtThuongHieu.getText().trim());
            sp.setHeDieuHanh(txtHDH.getText().trim());
            sp.setChipXuLy(txtChip.getText().trim());
            sp.setXuatXu(txtXuatXu.getText().trim());
            try {
                sp.setKichThuocMan(Double.parseDouble(txtMan.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Kích thước màn chỉ nhập số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                isOK = false;
            }
            try {
                sp.setDungLuongPin(Integer.parseInt(txtPin.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Dung lượng pin chỉ nhập số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                isOK = false;
            }
            try {
                sp.setGiaNhap(Integer.parseInt(txtGiaNhap.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Giá nhập phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                isOK = false;
            }
            try {
                sp.setGiaBan(Integer.parseInt(txtGiaBan.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Giá bán phải là số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                isOK = false;
            }
            if (isOK) {
                if (new SanPhamDAO().SuaSanPham(sp)) {
                    JOptionPane.showMessageDialog(this, "Sửa thành công!");
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Sửa thất bại!");
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed
    public void setEditData(SanPham sp) {
        ID = sp.getMaSP();
        txtChip.setText(sp.getChipXuLy());
        txtGiaNhap.setText(sp.getGiaNhap() + "");
        txtGiaBan.setText(sp.getGiaBan() + "");
        txtHDH.setText(sp.getHeDieuHanh());
        txtMan.setText(sp.getKichThuocMan() + "");
        txtPin.setText(sp.getDungLuongPin() + "");
        txtTenSP.setText(sp.getTenSP());
        txtThuongHieu.setText(sp.getThuongHieu());
        txtXuatXu.setText(sp.getXuatXu());
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtChip;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtHDH;
    private javax.swing.JTextField txtMan;
    private javax.swing.JTextField txtPin;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtThuongHieu;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
