/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.NhanVienDAO;
import Modal.NhanVien;
import Modal.TaiKhoan;
import java.awt.Color;
import javax.swing.JPanel;
import Chat.EnhancedChatClient;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author vinhn
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private PanelSamPham pnSanPham = new PanelSamPham();
    private PanelKhachHang pnKhachHang = new PanelKhachHang();
    private PanelNCC pnNCC = new PanelNCC();
    private PanelNhanVien pnNV = new PanelNhanVien();
    private PanelTaiKhoan pnTK = new PanelTaiKhoan();
    private PanelThongKe pnThongKe = new PanelThongKe();
    private TaiKhoan taikhoan;
    private NhanVien nv;
    private EnhancedChatClient chatUI;

    public MainForm(TaiKhoan tk) {
        this.taikhoan = tk;
        initComponents();
        setLocationRelativeTo(null);
        this.nv = new NhanVienDAO().getNhanVienByID(taikhoan.getMaNV());
        lbTen.setText(nv.getTenNV());
        if (taikhoan.getQuyen() == 0) {
            lbChucVu.setText("Nhân viên");
            btnTaiKhoan.setEnabled(false);
            btnNhanVien.setEnabled(false);
            btnThongKe.setEnabled(false);
        } else {
            lbChucVu.setText("Quản lý");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new keeptoo.KGradientPanel();
        btnPhieuNhap = new javax.swing.JButton();
        pnProfile = new javax.swing.JPanel();
        lbTen = new javax.swing.JLabel();
        lbChucVu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSanPham = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();
        btnPhieuXuat = new javax.swing.JButton();
        btnNCC = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnTaiKhoan = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnChat = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        pnTrangChu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý kho hàng điện thoại");

        pnLeft.setkEndColor(new java.awt.Color(0, 0, 102));
        pnLeft.setkStartColor(new java.awt.Color(0, 204, 255));

        btnPhieuNhap.setBackground(java.awt.Color.white);
        btnPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPhieuNhap.setForeground(new java.awt.Color(0, 0, 0));
        btnPhieuNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/invoice.png"))); // NOI18N
        btnPhieuNhap.setText("Phiếu nhập");
        btnPhieuNhap.setBorderPainted(false);
        btnPhieuNhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhieuNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuNhapActionPerformed(evt);
            }
        });

        pnProfile.setBackground(new java.awt.Color(102, 204, 255));
        pnProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbTen.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lbTen.setForeground(new java.awt.Color(0, 0, 0));
        lbTen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTen.setText("Nguyễn Trương Quang Vinh");
        lbTen.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbChucVu.setForeground(new java.awt.Color(102, 102, 102));
        lbChucVu.setText("Quản lý");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnProfileLayout = new javax.swing.GroupLayout(pnProfile);
        pnProfile.setLayout(pnProfileLayout);
        pnProfileLayout.setHorizontalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnProfileLayout.setVerticalGroup(
            pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnProfileLayout.createSequentialGroup()
                        .addGroup(pnProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnProfileLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbTen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 8, Short.MAX_VALUE))))
        );

        btnSanPham.setBackground(java.awt.Color.white);
        btnSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSanPham.setForeground(new java.awt.Color(0, 0, 0));
        btnSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smartphone.png"))); // NOI18N
        btnSanPham.setText("Sản phẩm");
        btnSanPham.setBorderPainted(false);
        btnSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnKhachHang.setBackground(java.awt.Color.white);
        btnKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(0, 0, 0));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        btnKhachHang.setText("Khách hàng");
        btnKhachHang.setBorderPainted(false);
        btnKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });

        btnTrangChu.setBackground(new java.awt.Color(102, 204, 255));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(0, 0, 0));
        btnTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/house.png"))); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setBorderPainted(false);
        btnTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btnPhieuXuat.setBackground(java.awt.Color.white);
        btnPhieuXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPhieuXuat.setForeground(new java.awt.Color(0, 0, 0));
        btnPhieuXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N
        btnPhieuXuat.setText("Phiếu xuất");
        btnPhieuXuat.setBorderPainted(false);
        btnPhieuXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPhieuXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieuXuatActionPerformed(evt);
            }
        });

        btnNCC.setBackground(java.awt.Color.white);
        btnNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNCC.setForeground(new java.awt.Color(0, 0, 0));
        btnNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/courier.png"))); // NOI18N
        btnNCC.setText("Nhà cung cấp");
        btnNCC.setBorderPainted(false);
        btnNCC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNCCActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(java.awt.Color.white);
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/team.png"))); // NOI18N
        btnNhanVien.setText("Nhân viên");
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(java.awt.Color.white);
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(0, 0, 0));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bar-chart.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.setBorderPainted(false);
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnTaiKhoan.setBackground(java.awt.Color.white);
        btnTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTaiKhoan.setForeground(new java.awt.Color(0, 0, 0));
        btnTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile (2).png"))); // NOI18N
        btnTaiKhoan.setText("Tài khoản");
        btnTaiKhoan.setBorderPainted(false);
        btnTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiKhoanActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(java.awt.Color.red);
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setForeground(java.awt.Color.white);
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnChat.setBackground(java.awt.Color.white);
        btnChat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnChat.setForeground(new java.awt.Color(0, 0, 0));
        btnChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chat.png"))); // NOI18N
        btnChat.setText("Chat");
        btnChat.setBorderPainted(false);
        btnChat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChatActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setBackground(java.awt.Color.gray);
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDoiMatKhau.setForeground(java.awt.Color.white);
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhieuXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnDoiMatKhau)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnTrangChu)
                .addGap(18, 18, 18)
                .addComponent(btnSanPham)
                .addGap(18, 18, 18)
                .addComponent(btnKhachHang)
                .addGap(18, 18, 18)
                .addComponent(btnPhieuNhap)
                .addGap(18, 18, 18)
                .addComponent(btnPhieuXuat)
                .addGap(18, 18, 18)
                .addComponent(btnNCC)
                .addGap(18, 18, 18)
                .addComponent(btnNhanVien)
                .addGap(18, 18, 18)
                .addComponent(btnTaiKhoan)
                .addGap(18, 18, 18)
                .addComponent(btnThongKe)
                .addGap(18, 18, 18)
                .addComponent(btnChat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDoiMatKhau)
                .addContainerGap())
        );

        pnRight.setLayout(new java.awt.CardLayout());

        pnTrangChu.setBackground(java.awt.Color.white);
        pnTrangChu.setInheritsPopupMenu(true);

        jPanel1.setBackground(new java.awt.Color(240, 247, 250));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/encrypted.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/target.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 149, 177));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BẢO MẬT");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 149, 177));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CHÍNH XÁC");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 149, 177));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("HIỆU QUẢ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 149, 177));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Hệ thống quản lý kho hàng điện thoại");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/java.png"))); // NOI18N

        javax.swing.GroupLayout pnTrangChuLayout = new javax.swing.GroupLayout(pnTrangChu);
        pnTrangChu.setLayout(pnTrangChuLayout);
        pnTrangChuLayout.setHorizontalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTrangChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1149, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnTrangChuLayout.setVerticalGroup(
            pnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTrangChuLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnRight.add(pnTrangChu, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPhieuNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuNhapActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(new Color(102, 204, 255));
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        PanelPhieuNhap pnPN = new PanelPhieuNhap(taikhoan);
        pnRight.add(pnPN);
        pnRight.repaint();
        pnRight.revalidate();
        pnPN.setDefault();
        pnPN.resetPanel();
    }//GEN-LAST:event_btnPhieuNhapActionPerformed

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(new Color(102, 204, 255));
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnSanPham);
        pnRight.repaint();
        pnRight.revalidate();
        pnSanPham.showTable();
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(new Color(102, 204, 255));
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnKhachHang);
        pnRight.repaint();
        pnRight.revalidate();
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        btnTrangChu.setBackground(new Color(102, 204, 255));
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnTrangChu);
        pnRight.repaint();
        pnRight.revalidate();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnPhieuXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieuXuatActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(new Color(102, 204, 255));
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        PanelPhieuXuat pnPX = new PanelPhieuXuat(taikhoan);
        pnRight.add(pnPX);
        pnRight.repaint();
        pnRight.revalidate();
        pnPX.setDefault();
    }//GEN-LAST:event_btnPhieuXuatActionPerformed

    private void btnNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNCCActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(new Color(102, 204, 255));
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnNCC);
        pnRight.repaint();
        pnRight.revalidate();
    }//GEN-LAST:event_btnNCCActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(new Color(102, 204, 255));
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnNV);
        pnRight.repaint();
        pnRight.revalidate();
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(new Color(102, 204, 255));
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnThongKe);
        pnThongKe.loadThongKe();
        pnRight.repaint();
        pnRight.revalidate();

    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiKhoanActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(new Color(102, 204, 255));
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setBackground(Color.WHITE);
        pnRight.removeAll();
        pnRight.add(pnTK);
        pnRight.repaint();
        pnRight.revalidate();
    }//GEN-LAST:event_btnTaiKhoanActionPerformed

    private void btnChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChatActionPerformed
        btnTrangChu.setBackground(Color.WHITE);
        btnKhachHang.setBackground(Color.WHITE);
        btnNCC.setBackground(Color.WHITE);
        btnNhanVien.setBackground(Color.WHITE);
        btnPhieuNhap.setBackground(Color.WHITE);
        btnPhieuXuat.setBackground(Color.WHITE);
        btnSanPham.setBackground(Color.WHITE);
        btnTaiKhoan.setBackground(Color.WHITE);
        btnThongKe.setBackground(Color.WHITE);
        btnChat.setEnabled(false);
//        btnChat.setBackground(new Color(102, 204, 255));
        NhanVien nv = new NhanVienDAO().getNhanVienByID(taikhoan.getMaNV());

        new Thread(() -> {
            SwingUtilities.invokeLater(() -> {
                chatUI = new EnhancedChatClient(nv.getTenNV(), btnChat);
                chatUI.setVisible(true);
            });
        }).start();


    }//GEN-LAST:event_btnChatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        if (chatUI != null && chatUI.isDisplayable()) {
        chatUI.dispose();
        chatUI.closeConnection();
    }
        dispose();
        SwingUtilities.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        DiologDoiMK dlDoiMK = new DiologDoiMK(this, true, taikhoan);
        dlDoiMK.setVisible(true);

    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public void capNhatPanel(JPanel pn) {
        pnRight.removeAll();
        pnRight.add(pn);
        pnRight.repaint();
        pnRight.revalidate();

    }

    public void setTaiKhoan(TaiKhoan tk) {
        taikhoan = tk;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChat;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnNCC;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhieuNhap;
    private javax.swing.JButton btnPhieuXuat;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnTaiKhoan;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbChucVu;
    private javax.swing.JLabel lbTen;
    private keeptoo.KGradientPanel pnLeft;
    private javax.swing.JPanel pnProfile;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnTrangChu;
    // End of variables declaration//GEN-END:variables

}
