/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.TaiKhoanDAO;
import Helper.MaHoaUtil;
import Modal.TaiKhoan;
import java.util.ArrayDeque;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinhn
 */
public class PanelTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form PanelSamPham
     */
    private MainForm mainForm;

    public PanelTaiKhoan() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 247, 250));
        setPreferredSize(new java.awt.Dimension(1164, 792));

        pnChucNang.setBackground(java.awt.Color.white);

        btnThem.setBackground(java.awt.Color.white);
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(1, 99, 181));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(java.awt.Color.white);
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(1, 99, 181));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(java.awt.Color.white);
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(1, 99, 181));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(780, Short.MAX_VALUE))
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setForeground(java.awt.Color.white);

        tableTK.setBackground(java.awt.Color.white);
        tableTK.setForeground(java.awt.Color.black);
        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên đăng nhập", "Mật khẩu", "Quyền", "Trạng thái"
            }
        ));
        jScrollPane1.setViewportView(tableTK);
        if (tableTK.getColumnModel().getColumnCount() > 0) {
            tableTK.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        DiologChonNV dlChonNV = new DiologChonNV(mainForm, true);
        dlChonNV.setVisible(true);
        showTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        ArrayList<TaiKhoan> list = new TaiKhoanDAO().getListTK();
        int SelectedIndex = tableTK.getSelectedRow();
        if (list.size() == 0)
            JOptionPane.showMessageDialog(this, "Chưa có nhân viên nào để sửa");
        else if (SelectedIndex == -1)
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên cần sửa!");
        else {
            int SelectedID = (int) tableTK.getValueAt(SelectedIndex, 0);
            DiologSuaTK dlSuaTK = new DiologSuaTK(mainForm, true);
            dlSuaTK.setEditData(list.get(SelectedIndex));
            dlSuaTK.setVisible(true);
            showTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tableTK.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn tài khoản cần xóa!");
        } else {
            int dongy = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (dongy == JOptionPane.YES_OPTION) {
                int ID = (int) tableTK.getValueAt(tableTK.getSelectedRow(), 0);
                if (new TaiKhoanDAO().XoaTKByID(ID)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }
        }
        showTable();
    }//GEN-LAST:event_btnXoaActionPerformed
    private void showTable() {
        ArrayList<TaiKhoan> list = new TaiKhoanDAO().getListTK();
        DefaultTableModel model = (DefaultTableModel) tableTK.getModel();
        model.setRowCount(0);
        String quyen, trangthai;
        for (TaiKhoan tk : list) {
            if (tk.getQuyen() == 0) {
                quyen = "Nhân viên";
            } else {
                quyen = "Quản lý";
            }
            if (tk.getTrangThai() == 1) {
                trangthai = "Hoạt động";
            } else {
                trangthai = "Ngưng hoạt động";
            }
            model.addRow(new Object[]{tk.getMaNV(), tk.getTenDangNhap(), MaHoaUtil.decrypt(tk.getMatKhau()), quyen, trangthai});
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JTable tableTK;
    // End of variables declaration//GEN-END:variables
}
