/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.CTPhieuNhapDAO;
import Controller.NhaCungCapDAO;
import Controller.NhanVienDAO;
import Controller.PhieuNhapDAO;
import Controller.SanPhamDAO;
import Modal.CTPhieuNhap;
import Modal.KhachHang;
import Modal.NhaCungCap;
import Modal.NhanVien;
import Modal.PhieuNhapKho;
import Modal.SanPham;
import Modal.TaiKhoan;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vinhn
 */
public class PanelPhieuNhap extends javax.swing.JPanel {

    /**
     * Creates new form PanelSamPham
     */
    int TongTien = 0;
    NumberFormat tien = NumberFormat.getInstance(new Locale("vi", "VN"));
    private ArrayList<SanPham> listSP;
    private ArrayList<CTPhieuNhap> listGioHang = new ArrayList<>();
    private ArrayList<PhieuNhapKho> listPN;
    private ArrayList<NhanVien> listNV;
    private ArrayList<NhaCungCap> listNCC;
    int STT = 0;
    private MainForm mainForm;
    private TaiKhoan taikhoan;
    private NhanVien nhanvien;

    public PanelPhieuNhap(TaiKhoan tk) {
        this.taikhoan = tk;
        initComponents();
        showTableSP();
        getSelectRowSP();
        getSelectRowGH();
        this.nhanvien = new NhanVienDAO().getNhanVienByID(tk.getMaNV());
        txtNV.setText(nhanvien.getTenNV());
        fillBoxNCC();
        fillBoxLoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPhieuNhap = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePN = new javax.swing.JTable();
        pnChucNang3 = new javax.swing.JPanel();
        btnThemPhieu = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        btnXoaPhieu = new javax.swing.JButton();
        pnLocPhieu = new javax.swing.JPanel();
        boxLocNCC = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        boxLocNV = new javax.swing.JComboBox<>();
        pnThemPhieuNhap = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableGiohang = new javax.swing.JTable();
        txtMaSP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThemGio = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        txtMaPN = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        boxNCC = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        btnNhapHang = new javax.swing.JButton();
        txtNV = new javax.swing.JTextField();
        txtTongTien = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 247, 250));
        setPreferredSize(new java.awt.Dimension(1164, 792));
        setLayout(new java.awt.CardLayout());

        pnPhieuNhap.setPreferredSize(new java.awt.Dimension(1161, 792));

        jScrollPane2.setBackground(java.awt.Color.white);
        jScrollPane2.setForeground(java.awt.Color.white);

        tablePN.setBackground(java.awt.Color.white);
        tablePN.setForeground(java.awt.Color.black);
        tablePN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã PN", "Nhà cung cấp", "Nhân viên nhập", "Thời gian", "Tổng tiền"
            }
        ));
        jScrollPane2.setViewportView(tablePN);

        pnChucNang3.setBackground(java.awt.Color.white);
        pnChucNang3.setPreferredSize(new java.awt.Dimension(225, 780));

        btnThemPhieu.setBackground(java.awt.Color.white);
        btnThemPhieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemPhieu.setForeground(new java.awt.Color(1, 99, 181));
        btnThemPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnThemPhieu.setText("Thêm phiếu");
        btnThemPhieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuActionPerformed(evt);
            }
        });

        btnChiTiet.setBackground(java.awt.Color.white);
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(1, 99, 181));
        btnChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/information.png"))); // NOI18N
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        btnXoaPhieu.setBackground(java.awt.Color.white);
        btnXoaPhieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaPhieu.setForeground(new java.awt.Color(1, 99, 181));
        btnXoaPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        btnXoaPhieu.setText("Xóa");
        btnXoaPhieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoaPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhieuActionPerformed(evt);
            }
        });

        pnLocPhieu.setBackground(new java.awt.Color(255, 255, 255));
        pnLocPhieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc phiếu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        boxLocNCC.setBackground(java.awt.Color.white);
        boxLocNCC.setForeground(new java.awt.Color(0, 0, 0));
        boxLocNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        boxLocNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLocNCCActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Nhà cung cấp");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nhân viên nhập");

        boxLocNV.setBackground(java.awt.Color.white);
        boxLocNV.setForeground(new java.awt.Color(0, 0, 0));
        boxLocNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLocNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLocPhieuLayout = new javax.swing.GroupLayout(pnLocPhieu);
        pnLocPhieu.setLayout(pnLocPhieuLayout);
        pnLocPhieuLayout.setHorizontalGroup(
            pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLocPhieuLayout.createSequentialGroup()
                        .addGroup(pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boxLocNCC, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxLocNV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        pnLocPhieuLayout.setVerticalGroup(
            pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocPhieuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxLocNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxLocNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnChucNang3Layout = new javax.swing.GroupLayout(pnChucNang3);
        pnChucNang3.setLayout(pnChucNang3Layout);
        pnChucNang3Layout.setHorizontalGroup(
            pnChucNang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNang3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChucNang3Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(pnChucNang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(pnLocPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnChucNang3Layout.setVerticalGroup(
            pnChucNang3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNang3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThemPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnLocPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnPhieuNhapLayout = new javax.swing.GroupLayout(pnPhieuNhap);
        pnPhieuNhap.setLayout(pnPhieuNhapLayout);
        pnPhieuNhapLayout.setHorizontalGroup(
            pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPhieuNhapLayout.createSequentialGroup()
                .addComponent(pnChucNang3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE))
        );
        pnPhieuNhapLayout.setVerticalGroup(
            pnPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChucNang3, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        add(pnPhieuNhap, "card2");

        pnLeft.setBackground(java.awt.Color.white);

        jScrollPane3.setBackground(java.awt.Color.white);

        tableSanPham.setBackground(java.awt.Color.white);
        tableSanPham.setForeground(java.awt.Color.black);
        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng"
            }
        ));
        jScrollPane3.setViewportView(tableSanPham);

        jScrollPane4.setBackground(java.awt.Color.white);
        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane4.setForeground(java.awt.Color.white);

        tableGiohang.setBackground(java.awt.Color.white);
        tableGiohang.setForeground(java.awt.Color.black);
        tableGiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã SP", "Tên sản phẩm", "Đơn giá", "Số lượng"
            }
        ));
        jScrollPane4.setViewportView(tableGiohang);

        txtMaSP.setEditable(false);
        txtMaSP.setBackground(java.awt.Color.white);
        txtMaSP.setForeground(java.awt.Color.black);
        txtMaSP.setDisabledTextColor(java.awt.Color.black);
        txtMaSP.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.black);
        jLabel18.setText("Mã SP");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.black);
        jLabel19.setText("Tên sản phẩm");

        txtTenSP.setEditable(false);
        txtTenSP.setBackground(java.awt.Color.white);
        txtTenSP.setForeground(java.awt.Color.black);
        txtTenSP.setDisabledTextColor(java.awt.Color.black);
        txtTenSP.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.black);
        jLabel20.setText("Giá nhập");

        txtGiaNhap.setEditable(false);
        txtGiaNhap.setBackground(java.awt.Color.white);
        txtGiaNhap.setForeground(java.awt.Color.black);
        txtGiaNhap.setDisabledTextColor(java.awt.Color.black);
        txtGiaNhap.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.black);
        jLabel21.setText("Số lượng");

        txtSoLuong.setBackground(java.awt.Color.white);
        txtSoLuong.setForeground(java.awt.Color.black);
        txtSoLuong.setDisabledTextColor(java.awt.Color.black);

        btnThemGio.setBackground(new java.awt.Color(51, 153, 0));
        btnThemGio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemGio.setForeground(java.awt.Color.white);
        btnThemGio.setText("Thêm vào giỏ");
        btnThemGio.setEnabled(false);
        btnThemGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGioActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 204, 0));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(java.awt.Color.white);
        btnSua.setText("Sửa ");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 51));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(java.awt.Color.white);
        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLeftLayout.createSequentialGroup()
                                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnLeftLayout.createSequentialGroup()
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnLeftLayout.createSequentialGroup()
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(txtTenSP)))
                                    .addGroup(pnLeftLayout.createSequentialGroup()
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLeftLayout.createSequentialGroup()
                                .addComponent(btnThemGio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))))))
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtMaSP))
                        .addGap(18, 18, 18)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong)))
                        .addGap(97, 97, 97)
                        .addComponent(btnThemGio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
        );

        pnRight.setBackground(java.awt.Color.white);

        txtMaPN.setBackground(java.awt.Color.white);
        txtMaPN.setForeground(java.awt.Color.black);
        txtMaPN.setDisabledTextColor(java.awt.Color.black);
        txtMaPN.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(java.awt.Color.black);
        jLabel22.setText("Mã Phiếu Nhập");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(java.awt.Color.black);
        jLabel23.setText("Nhân viên nhập");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(java.awt.Color.black);
        jLabel24.setText("Nhà cung cấp");

        boxNCC.setBackground(java.awt.Color.white);
        boxNCC.setForeground(java.awt.Color.black);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel25.setForeground(java.awt.Color.red);
        jLabel25.setText("TỔNG TIỀN:");

        btnNhapHang.setBackground(new java.awt.Color(0, 153, 0));
        btnNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNhapHang.setForeground(java.awt.Color.white);
        btnNhapHang.setText("Nhập hàng");
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        txtNV.setBackground(java.awt.Color.white);
        txtNV.setForeground(java.awt.Color.black);
        txtNV.setDisabledTextColor(java.awt.Color.black);
        txtNV.setEnabled(false);
        txtNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNVActionPerformed(evt);
            }
        });

        txtTongTien.setBackground(java.awt.Color.white);
        txtTongTien.setForeground(java.awt.Color.black);
        txtTongTien.setText("0đ");
        txtTongTien.setDisabledTextColor(java.awt.Color.black);
        txtTongTien.setEnabled(false);

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(txtMaPN)
                    .addComponent(boxNCC, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(txtNV)
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(12, 12, 12)
                .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout pnThemPhieuNhapLayout = new javax.swing.GroupLayout(pnThemPhieuNhap);
        pnThemPhieuNhap.setLayout(pnThemPhieuNhapLayout);
        pnThemPhieuNhapLayout.setHorizontalGroup(
            pnThemPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnThemPhieuNhapLayout.setVerticalGroup(
            pnThemPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemPhieuNhapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemPhieuNhapLayout.createSequentialGroup()
                        .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(pnThemPhieuNhap, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuActionPerformed
        this.removeAll();
        this.add(pnThemPhieuNhap);
        this.repaint();
        this.revalidate();
        txtMaPN.setText("PN" + TangMaPN());
        fillBoxNCC();
    }//GEN-LAST:event_btnThemPhieuActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        if (tablePN.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu cần xem!");
        } else {
            PhieuNhapKho pn = new PhieuNhapDAO().getPNbyID((int) tablePN.getValueAt(tablePN.getSelectedRow(), 0));
            diologChiTietPN dlChiTietPN = new diologChiTietPN(mainForm, true, pn);
            dlChiTietPN.setVisible(true);
        }
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        TongTien = 0;
        int select = tableGiohang.getSelectedRow();
        CTPhieuNhap ctpn = listGioHang.get(select);
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng!");
        } else {
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                if (sl <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
                } else {
                    ctpn.setSoLuong(sl);
                    listGioHang.set(select, ctpn);
                    JOptionPane.showMessageDialog(this, "Sửa thành công!");
                    showGioHang(listGioHang);
                    tinhTien();
                    resetTXT();
                    btnSua.setEnabled(false);
                    btnXoa.setEnabled(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng chỉ nhập số!");
            }

        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNVActionPerformed

    private void btnThemGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGioActionPerformed
        TongTien = 0;
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng!");
        } else {
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                int select = tableSanPham.getSelectedRow();
                listSP = new SanPhamDAO().getListSP();
                SanPham sp = listSP.get(select);
                CTPhieuNhap ctpn = new CTPhieuNhap(TangMaPN(), sp.getMaSP(), Integer.parseInt(txtSoLuong.getText()), sp.getGiaNhap());
                listGioHang.add(ctpn);
                showGioHang(listGioHang);
                tinhTien();
                txtSoLuong.setText("");
                tableSanPham.clearSelection();
                btnThemGio.setEnabled(false);
                txtGiaNhap.setText("");
                txtMaSP.setText("");
                txtTenSP.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng chỉ nhập số!");
            }

        }
    }//GEN-LAST:event_btnThemGioActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            int select = tableGiohang.getSelectedRow();
            listGioHang.remove(select);
            showGioHang(listGioHang);
            tinhTien();
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            resetTXT();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        if (tableGiohang.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa thêm sản phẩm cần nhập!");
        } else {
            PhieuNhapKho pn = new PhieuNhapKho();
            pn.setMaPN(TangMaPN());
            pn.setMaNCC(getChonMaNCC(boxNCC.getSelectedIndex()));
            pn.setMaNVNhap(nhanvien.getMaNV());
            pn.setTongTien(TongTien);
            int dongy = JOptionPane.showConfirmDialog(this, "bạn có chắc chắn muốn tạo phiếu?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (dongy == JOptionPane.YES_OPTION) {
                if (new PhieuNhapDAO().ThemPhieuNhap(pn)) {
                    for (CTPhieuNhap ctpn : listGioHang) {
                        new CTPhieuNhapDAO().ThemCTPN(ctpn);
                        new SanPhamDAO().CongSoLuong(ctpn.getMaSP(), ctpn.getSoLuong());
                    }
                    JOptionPane.showMessageDialog(this, "Tạo thành công");
                    setDefault();
                } else {
                    JOptionPane.showMessageDialog(this, "Tạo thất bại!");
                }
            }
        }
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void btnXoaPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhieuActionPerformed
        if (tablePN.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn phiếu cần xóa");
        } else {
            int dongy = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (dongy == JOptionPane.YES_OPTION) {
                int id = (int) tablePN.getValueAt(tablePN.getSelectedRow(), 0);
                if (new PhieuNhapDAO().XoaPhieuNhapByID(id)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    showTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Xáo thất bại!");
                }

            }
        }
    }//GEN-LAST:event_btnXoaPhieuActionPerformed

    private void boxLocNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLocNCCActionPerformed
        filterPhieuNhap();
    }//GEN-LAST:event_boxLocNCCActionPerformed

    private void boxLocNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLocNVActionPerformed
        filterPhieuNhap();
    }//GEN-LAST:event_boxLocNVActionPerformed
    public void setDefault() {
        this.removeAll();
        this.add(pnPhieuNhap);
        this.repaint();
        this.revalidate();
        showTable();
    }

    public void resetTXT() {
        txtGiaNhap.setText("");
        txtMaSP.setText("");
        txtSoLuong.setText("");
        txtTenSP.setText("");
    }

    private void getSelectRowSP() {
        tableSanPham.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                listSP = new SanPhamDAO().getListSP();
                tableGiohang.clearSelection();
                btnSua.setEnabled(false);
                btnXoa.setEnabled(false);
                int SelectedRow = tableSanPham.getSelectedRow();
                if (SelectedRow == -1) {
                } else {
                    SanPham sp = listSP.get(SelectedRow);
                    txtMaSP.setText(sp.getMaSP() + "");
                    txtTenSP.setText(sp.getTenSP());
                    txtGiaNhap.setText(tien.format(sp.getGiaNhap()) + "đ");
                    btnThemGio.setEnabled(true);
                    txtSoLuong.setText("");
                }
            }
        });
    }

    private void getSelectRowGH() {
        tableGiohang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int SelectedRow = tableGiohang.getSelectedRow();
                tableSanPham.clearSelection();
                btnThemGio.setEnabled(false);
                if (SelectedRow == -1) {
                } else {
                    CTPhieuNhap ctpn = listGioHang.get(SelectedRow);
                    txtMaSP.setText(ctpn.getMaSP() + "");
                    txtTenSP.setText(new SanPhamDAO().getSPbyID(ctpn.getMaSP()).getTenSP());
                    txtGiaNhap.setText(tien.format(ctpn.getGia()) + "đ");
                    txtSoLuong.setText(String.valueOf(ctpn.getSoLuong()));
                    btnSua.setEnabled(true);
                    btnXoa.setEnabled(true);
                }
            }
        });
    }

    private void showTableSP() {
        listSP = new SanPhamDAO().getListSP();
        DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
        model.setRowCount(0);
        for (SanPham sp : listSP) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(),
                sp.getSoLuong()});
        }
    }

    private void showGioHang(ArrayList<CTPhieuNhap> list) {
        DefaultTableModel model = (DefaultTableModel) tableGiohang.getModel();
        model.setRowCount(0);
        STT = 0;
        TongTien = 0;
        for (CTPhieuNhap ctpn : list) {
            SanPham sp = new SanPhamDAO().getSPbyID(ctpn.getMaSP());
            Object[] giohang = {++STT, ctpn.getMaSP(), sp.getTenSP(), tien.format(ctpn.getGia()) + "đ", ctpn.getSoLuong()};
            model.addRow(giohang);
        }
    }

    private void showTable() {
        listPN = new PhieuNhapDAO().getListPhieuNhap();
        DefaultTableModel model = (DefaultTableModel) tablePN.getModel();
        model.setRowCount(0);
        for (PhieuNhapKho pn : listPN) {
            NhanVien nv = new NhanVienDAO().getNhanVienByID(pn.getMaNVNhap());
            NhaCungCap ncc = new NhaCungCapDAO().getNCCByID(pn.getMaNCC());
            model.addRow(new Object[]{pn.getMaPN(), ncc.getTenNCC(), nv.getTenNV(), pn.getThoiGian(), tien.format(pn.getTongTien()) + "đ"});
        }
    }

    private void tinhTien() {
        if (listGioHang.size() == 0) {
            txtTongTien.setText("0đ");
            TongTien = 0;
        } else {
            for (CTPhieuNhap i : listGioHang) {
                TongTien += i.getGia() * i.getSoLuong();
            }
            txtTongTien.setText(tien.format(TongTien) + "đ");
        }
    }

    public void resetPanel() {
        STT = 0;
        DefaultTableModel model = (DefaultTableModel) tableGiohang.getModel();
        model.setRowCount(0);
        txtGiaNhap.setText("");
        txtMaPN.setText("");
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtSoLuong.setText("");
        txtTongTien.setText("0đ");
        btnThemGio.setEnabled(false);
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
        tableGiohang.removeAll();
        tableSanPham.clearSelection();
        listGioHang.clear();
        TongTien = 0;
    }

    private int TangMaPN() {
        int mapn = 0;
        listPN = new PhieuNhapDAO().getAllPhieuNhap();
        if (listPN.size() == 0) {
            mapn = 1;
        } else {
            PhieuNhapKho pn = new PhieuNhapKho();
            pn = listPN.get(listPN.size() - 1);
            mapn = pn.getMaPN() + 1;
        }
        return mapn;
    }

    public void fillBoxNCC() {
        listNCC = new NhaCungCapDAO().getListNCC();
        boxNCC.removeAllItems();
        for (NhaCungCap ncc : listNCC) {
            boxNCC.addItem(ncc.getTenNCC());
        }
    }

    public int getChonMaNCC(int vt) {
        ArrayList<NhaCungCap> list = new NhaCungCapDAO().getListNCC();
        NhaCungCap ncc = list.get(vt);
        return ncc.getMaNCC();
    }

    private void filterPhieuNhap() {
        String nhaCungCap = boxLocNCC.getSelectedItem() != null
                ? boxLocNCC.getSelectedItem().toString()
                : "Tất cả";
        String nhanVien = boxLocNV.getSelectedItem() != null
                ? boxLocNV.getSelectedItem().toString()
                : "Tất cả";

        DefaultTableModel model = (DefaultTableModel) tablePN.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablePN.setRowSorter(sorter);

        List<RowFilter<Object, Object>> filters = new ArrayList<>();

        if (!nhaCungCap.equals("Tất cả")) {
            filters.add(RowFilter.regexFilter(Pattern.quote(nhaCungCap), 1)); // cột 1: Nhà cung cấp
        }

        if (!nhanVien.equals("Tất cả")) {
            filters.add(RowFilter.regexFilter(Pattern.quote(nhanVien), 2)); // cột 2: Nhân viên nhập
        }

        if (filters.isEmpty()) {
            sorter.setRowFilter(null); // Không lọc gì cả
        } else {
            sorter.setRowFilter(RowFilter.andFilter(filters));
        }
    }

    private void fillBoxLoc() {
        listNV = new NhanVienDAO().getListNV();
        listNCC = new NhaCungCapDAO().getListNCC();
        boxLocNCC.removeAllItems();
        boxLocNV.removeAllItems();
        boxLocNCC.addItem("Tất cả");
        boxLocNV.addItem("Tất cả");
        for (NhanVien nv : listNV) {
            boxLocNV.addItem(nv.getTenNV());
        }
        for (NhaCungCap ncc : listNCC) {
            boxLocNCC.addItem(ncc.getTenNCC());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxLocNCC;
    private javax.swing.JComboBox<String> boxLocNV;
    private javax.swing.JComboBox<String> boxNCC;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemGio;
    private javax.swing.JButton btnThemPhieu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaPhieu;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnChucNang3;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLocPhieu;
    private javax.swing.JPanel pnPhieuNhap;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnThemPhieuNhap;
    private javax.swing.JTable tableGiohang;
    private javax.swing.JTable tablePN;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JTextField txtMaPN;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNV;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
