/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Modal.SanPham;
import Controller.SanPhamDAO;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author vinhn
 */
public class PanelSamPham extends javax.swing.JPanel {

    /**
     * Creates new form PanelSamPham
     */
    private ArrayList<SanPham> listSP;
    private ArrayList<SanPham> listFind;
    private MainForm mainForm;
    public int SelectedID = 0;

    public PanelSamPham() {
        initComponents();
        showTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnChucNang = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSP = new javax.swing.JTable();

        setBackground(new java.awt.Color(240, 247, 250));
        setPreferredSize(new java.awt.Dimension(1164, 792));

        pnChucNang.setBackground(java.awt.Color.white);

        btnThem.setBackground(java.awt.Color.white);
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(1, 99, 181));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(java.awt.Color.white);
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setForeground(new java.awt.Color(1, 99, 181));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pencil.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(java.awt.Color.white);
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(1, 99, 181));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        txtTimKiem.setBackground(java.awt.Color.white);
        txtTimKiem.setToolTipText("");
        txtTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTimKiem.setName(""); // NOI18N

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 204));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimKiem)
                .addGap(52, 52, 52))
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua))
                .addGap(18, 18, 18))
        );

        jScrollPane1.setBackground(java.awt.Color.white);
        jScrollPane1.setForeground(java.awt.Color.white);

        tableSP.setBackground(java.awt.Color.white);
        tableSP.setForeground(java.awt.Color.black);
        tableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng", "Thương hiệu", "Hệ điều hành", "Kích thước màn", "Chip xử lý", "Dung lượng pin", "Xuất xứ", "Giá nhập", "Giá bán"
            }
        ));
        jScrollPane1.setViewportView(tableSP);
        if (tableSP.getColumnModel().getColumnCount() > 0) {
            tableSP.getColumnModel().getColumn(0).setPreferredWidth(15);
            tableSP.getColumnModel().getColumn(1).setPreferredWidth(150);
            tableSP.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableSP.getColumnModel().getColumn(3).setPreferredWidth(80);
            tableSP.getColumnModel().getColumn(4).setPreferredWidth(80);
            tableSP.getColumnModel().getColumn(5).setPreferredWidth(80);
            tableSP.getColumnModel().getColumn(6).setPreferredWidth(100);
            tableSP.getColumnModel().getColumn(7).setPreferredWidth(80);
            tableSP.getColumnModel().getColumn(8).setPreferredWidth(80);
            tableSP.getColumnModel().getColumn(9).setPreferredWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnChucNang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (txtTimKiem.getText().trim().isEmpty())
            showTable();
        else
            showFindSP();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        DiologThemSP dlThemSP = new DiologThemSP(mainForm, true);
        dlThemSP.setVisible(true);
        showTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        ArrayList<SanPham> listSP = new SanPhamDAO().getListSP();
        int SelectedIndex = tableSP.getSelectedRow();
        if (listSP.size() == 0)
            JOptionPane.showMessageDialog(this, "Chưa có sản phẩm nào để sửa");
        else if (SelectedIndex == -1)
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm cần sửa!");
        else {
            SelectedID = (int) tableSP.getValueAt(SelectedIndex, 0);
            DiologSuaSP dlSuaSP = new DiologSuaSP(mainForm, true);
            dlSuaSP.setEditData(listSP.get(SelectedIndex));
            dlSuaSP.setVisible(true);
            showTable();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (tableSP.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn sản phẩm cần xóa!");
        } else {
            int dongy = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (dongy == JOptionPane.YES_OPTION) {
                int ID = (int) tableSP.getValueAt(tableSP.getSelectedRow(), 0);
                if (new SanPhamDAO().XoaSanPhamByID(ID)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }
        }
        showTable();
    }//GEN-LAST:event_btnXoaActionPerformed
    public void showTable() {
        listSP = new SanPhamDAO().getListSP();
        DefaultTableModel model = (DefaultTableModel) tableSP.getModel();
        model.setRowCount(0);
        for (SanPham sp : listSP) {
            NumberFormat tien = NumberFormat.getInstance(new Locale("vi", "VN"));
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(),
                sp.getSoLuong(), sp.getThuongHieu(), sp.getHeDieuHanh(),
                sp.getKichThuocMan() + "inch", sp.getChipXuLy(), sp.getDungLuongPin() + "mah",
                sp.getXuatXu(), tien.format(sp.getGiaNhap()) + "đ", tien.format(sp.getGiaBan()) + "đ"});
        }
    }

    private void showFindSP() {
        listFind = new SanPhamDAO().getFindSP(txtTimKiem.getText().trim());
        DefaultTableModel model = (DefaultTableModel) tableSP.getModel();
        model.setRowCount(0);
        for (SanPham sp : listFind) {
            NumberFormat tien = NumberFormat.getInstance(new Locale("vi", "VN"));
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(),
                sp.getSoLuong(), sp.getThuongHieu(), sp.getHeDieuHanh(),
                sp.getKichThuocMan() + "inch", sp.getChipXuLy(), sp.getDungLuongPin() + "mah",
                sp.getXuatXu(), tien.format(sp.getGiaNhap()) + "đ", tien.format(sp.getGiaBan()) + "đ"});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JTable tableSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
