/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.CTPhieuXuatDAO;
import Controller.KhachHangDAO;
import Controller.NhanVienDAO;
import Controller.PhieuXuatDAO;
import Controller.SanPhamDAO;
import Modal.CTPhieuXuat;
import Modal.KhachHang;
import Modal.NhanVien;
import Modal.PhieuXuatKho;
import Modal.SanPham;
import Modal.TaiKhoan;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import javax.crypto.KEM;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vinhn
 */
public class PanelPhieuXuat extends javax.swing.JPanel {

    /**
     * Creates new form PanelSamPham
     */
    int TongTien = 0;
    NumberFormat tien = NumberFormat.getInstance(new Locale("vi", "VN"));
    private ArrayList<SanPham> listSP;
    private ArrayList<CTPhieuXuat> listGioHang = new ArrayList<>();
    private ArrayList<PhieuXuatKho> listPX;
    private ArrayList<NhanVien> listNV;
    private ArrayList<KhachHang> listKH;
    int STT = 0;
    private TaiKhoan taikhoan;
    private NhanVien nhanvien;
    private MainForm mainForm;

    public PanelPhieuXuat(TaiKhoan tk) {
        initComponents();
        this.taikhoan = tk;
        showTableSP();
        getSelectRowSP();
        getSelectRowGH();
        this.nhanvien = new NhanVienDAO().getNhanVienByID(tk.getMaNV());
        txtNVXuat.setText(nhanvien.getTenNV());
        fillBoxKH();
        fillBoxLoc();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPhieuXuat = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePX = new javax.swing.JTable();
        pnChucNang = new javax.swing.JPanel();
        btnThemPhieu = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        btnXoaphieu = new javax.swing.JButton();
        pnLocPhieu = new javax.swing.JPanel();
        boxLocKH = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        boxLocNV = new javax.swing.JComboBox<>();
        pnThemPhieuXuat = new javax.swing.JPanel();
        pnLeft = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSanPham = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableGiohang = new javax.swing.JTable();
        txtMaSP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtGiaXuat = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnThemGio = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        pnRight = new javax.swing.JPanel();
        txtMaPX = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtNVXuat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        boxKH = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        btnNhapHang = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();

        setBackground(new java.awt.Color(240, 247, 250));
        setPreferredSize(new java.awt.Dimension(1161, 792));
        setLayout(new java.awt.CardLayout());

        pnPhieuXuat.setPreferredSize(new java.awt.Dimension(1164, 792));

        jScrollPane2.setBackground(java.awt.Color.white);
        jScrollPane2.setForeground(java.awt.Color.white);

        tablePX.setBackground(java.awt.Color.white);
        tablePX.setForeground(java.awt.Color.black);
        tablePX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã PX", "Khách hàng", "Nhân viên nhập", "Thời gian", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePX);
        if (tablePX.getColumnModel().getColumnCount() > 0) {
            tablePX.getColumnModel().getColumn(0).setPreferredWidth(30);
            tablePX.getColumnModel().getColumn(1).setPreferredWidth(200);
            tablePX.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        pnChucNang.setBackground(java.awt.Color.white);

        btnThemPhieu.setBackground(java.awt.Color.white);
        btnThemPhieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemPhieu.setForeground(new java.awt.Color(1, 99, 181));
        btnThemPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus.png"))); // NOI18N
        btnThemPhieu.setText("Thêm phiếu");
        btnThemPhieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemPhieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuActionPerformed(evt);
            }
        });

        btnChiTiet.setBackground(java.awt.Color.white);
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(1, 99, 181));
        btnChiTiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/information.png"))); // NOI18N
        btnChiTiet.setText("Chi tiết");
        btnChiTiet.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChiTiet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        btnXoaphieu.setBackground(java.awt.Color.white);
        btnXoaphieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaphieu.setForeground(new java.awt.Color(1, 99, 181));
        btnXoaphieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bin.png"))); // NOI18N
        btnXoaphieu.setText("Xóa");
        btnXoaphieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoaphieu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnXoaphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaphieuActionPerformed(evt);
            }
        });

        pnLocPhieu.setBackground(new java.awt.Color(255, 255, 255));
        pnLocPhieu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc phiếu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        boxLocKH.setBackground(java.awt.Color.white);
        boxLocKH.setForeground(new java.awt.Color(0, 0, 0));
        boxLocKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLocKHActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Khách hàng");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Nhân viên xuất");

        boxLocNV.setBackground(java.awt.Color.white);
        boxLocNV.setForeground(new java.awt.Color(0, 0, 0));
        boxLocNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxLocNVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLocPhieuLayout = new javax.swing.GroupLayout(pnLocPhieu);
        pnLocPhieu.setLayout(pnLocPhieuLayout);
        pnLocPhieuLayout.setHorizontalGroup(
            pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocPhieuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLocPhieuLayout.createSequentialGroup()
                        .addGroup(pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boxLocKH, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxLocNV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        pnLocPhieuLayout.setVerticalGroup(
            pnLocPhieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLocPhieuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxLocKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxLocNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnChucNangLayout = new javax.swing.GroupLayout(pnChucNang);
        pnChucNang.setLayout(pnChucNangLayout);
        pnChucNangLayout.setHorizontalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnChucNangLayout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addGroup(pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThemPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaphieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(pnLocPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnChucNangLayout.setVerticalGroup(
            pnChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnChucNangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnThemPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(pnLocPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnPhieuXuatLayout = new javax.swing.GroupLayout(pnPhieuXuat);
        pnPhieuXuat.setLayout(pnPhieuXuatLayout);
        pnPhieuXuatLayout.setHorizontalGroup(
            pnPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPhieuXuatLayout.createSequentialGroup()
                .addComponent(pnChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE))
        );
        pnPhieuXuatLayout.setVerticalGroup(
            pnPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnChucNang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        add(pnPhieuXuat, "card2");

        pnLeft.setBackground(java.awt.Color.white);

        jScrollPane3.setBackground(java.awt.Color.white);

        tableSanPham.setBackground(java.awt.Color.white);
        tableSanPham.setForeground(java.awt.Color.black);
        tableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableSanPham);

        jScrollPane4.setBackground(java.awt.Color.white);
        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane4.setForeground(java.awt.Color.white);

        tableGiohang.setBackground(java.awt.Color.white);
        tableGiohang.setForeground(java.awt.Color.black);
        tableGiohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Tên sản phẩm", "Đơn giá", "Số lượng"
            }
        ));
        jScrollPane4.setViewportView(tableGiohang);

        txtMaSP.setEditable(false);
        txtMaSP.setBackground(java.awt.Color.white);
        txtMaSP.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(java.awt.Color.black);
        jLabel18.setText("Mã SP");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(java.awt.Color.black);
        jLabel19.setText("Tên sản phẩm");

        txtTenSP.setEditable(false);
        txtTenSP.setBackground(java.awt.Color.white);
        txtTenSP.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(java.awt.Color.black);
        jLabel20.setText("Giá xuất");

        txtGiaXuat.setEditable(false);
        txtGiaXuat.setBackground(java.awt.Color.white);
        txtGiaXuat.setEnabled(false);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(java.awt.Color.black);
        jLabel21.setText("Số lượng");

        txtSoLuong.setBackground(java.awt.Color.white);

        btnThemGio.setBackground(new java.awt.Color(51, 153, 0));
        btnThemGio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemGio.setForeground(java.awt.Color.white);
        btnThemGio.setText("Thêm vào giỏ");
        btnThemGio.setEnabled(false);
        btnThemGio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemGioActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 204, 0));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(java.awt.Color.white);
        btnSua.setText("Sửa ");
        btnSua.setEnabled(false);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 51));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(java.awt.Color.white);
        btnXoa.setText("Xóa");
        btnXoa.setEnabled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addGap(44, 44, 44)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLeftLayout.createSequentialGroup()
                                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnLeftLayout.createSequentialGroup()
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(txtGiaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnLeftLayout.createSequentialGroup()
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(txtTenSP)))
                                    .addGroup(pnLeftLayout.createSequentialGroup()
                                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLeftLayout.createSequentialGroup()
                                .addComponent(btnThemGio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))))))
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnLeftLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(txtMaSP))
                        .addGap(18, 18, 18)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtGiaXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnLeftLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong)))
                        .addGap(97, 97, 97)
                        .addComponent(btnThemGio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        pnRight.setBackground(java.awt.Color.white);

        txtMaPX.setBackground(java.awt.Color.white);
        txtMaPX.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(java.awt.Color.black);
        jLabel22.setText("Mã Phiếu Xuất");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(java.awt.Color.black);
        jLabel23.setText("Nhân viên xuất");

        txtNVXuat.setBackground(java.awt.Color.white);
        txtNVXuat.setEnabled(false);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(java.awt.Color.black);
        jLabel24.setText("Khách hàng");

        boxKH.setBackground(java.awt.Color.white);
        boxKH.setForeground(java.awt.Color.black);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel25.setForeground(java.awt.Color.red);
        jLabel25.setText("TỔNG TIỀN:");

        btnNhapHang.setBackground(new java.awt.Color(0, 153, 0));
        btnNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNhapHang.setForeground(java.awt.Color.white);
        btnNhapHang.setText("Xuất hàng");
        btnNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapHangActionPerformed(evt);
            }
        });

        txtTongTien.setBackground(java.awt.Color.white);
        txtTongTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTongTien.setForeground(java.awt.Color.black);
        txtTongTien.setText("0đ");

        javax.swing.GroupLayout pnRightLayout = new javax.swing.GroupLayout(pnRight);
        pnRight.setLayout(pnRightLayout);
        pnRightLayout.setHorizontalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23)
                        .addComponent(txtNVXuat)
                        .addComponent(jLabel22)
                        .addComponent(txtMaPX)
                        .addComponent(boxKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                    .addGroup(pnRightLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnRightLayout.setVerticalGroup(
            pnRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRightLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaPX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNVXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout pnThemPhieuXuatLayout = new javax.swing.GroupLayout(pnThemPhieuXuat);
        pnThemPhieuXuat.setLayout(pnThemPhieuXuatLayout);
        pnThemPhieuXuatLayout.setHorizontalGroup(
            pnThemPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemPhieuXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pnRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnThemPhieuXuatLayout.setVerticalGroup(
            pnThemPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemPhieuXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThemPhieuXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemPhieuXuatLayout.createSequentialGroup()
                        .addComponent(pnRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        add(pnThemPhieuXuat, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemPhieuActionPerformed
        this.removeAll();
        this.add(pnThemPhieuXuat);
        this.repaint();
        this.revalidate();
        txtMaPX.setText("Px" + TangMaPX());
        fillBoxKH();
    }//GEN-LAST:event_btnThemPhieuActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        if (tablePX.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phiếu cần xem!");
        } else {
            PhieuXuatKho px = new PhieuXuatDAO().getPXbyID((int) tablePX.getValueAt(tablePX.getSelectedRow(), 0));
            diologChiTietPX dlChiTietPX = new diologChiTietPX(mainForm, true, px);
            dlChiTietPX.setVisible(true);
        }
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        TongTien = 0;
        int select = tableGiohang.getSelectedRow();
        CTPhieuXuat ctpx = listGioHang.get(select);
        SanPham sp = new SanPhamDAO().getSPbyID((int) tableGiohang.getValueAt(select, 1));
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng!");
        } else {
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                if (sl <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
                } else {
                    if (sl > sp.getSoLuong()) {
                        JOptionPane.showMessageDialog(this, "Quá số lượng hiện có!");
                    } else {
                        ctpx.setSoLuong(sl);
                        listGioHang.set(select, ctpx);
                        JOptionPane.showMessageDialog(this, "Sửa thành công!");
                        showGioHang(listGioHang);
                        showTableSP();
                        tinhTien();
                        resetTXT();
                        btnSua.setEnabled(false);
                        btnXoa.setEnabled(false);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng chỉ nhập số");
            }

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemGioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemGioActionPerformed
        TongTien = 0;
        if (txtSoLuong.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng!");
        } else {
            try {
                int sl = Integer.parseInt(txtSoLuong.getText());
                int select = tableSanPham.getSelectedRow();
                if (sl <= 0) {
                    JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0!");
                } else {
                    if (sl > (int)tableSanPham.getValueAt(select, 2)) {
                        JOptionPane.showMessageDialog(this, "Quá số lượng hiện có!");
                    } else {
                        listSP = new SanPhamDAO().getListSP();
                        SanPham sp = listSP.get(select);
                        CTPhieuXuat ctpx = new CTPhieuXuat(TangMaPX(), sp.getMaSP(), Integer.parseInt(txtSoLuong.getText()), sp.getGiaBan());
                        listGioHang.add(ctpx);
                        showGioHang(listGioHang);
                        tinhTien();
//                        int slmoi= (int)tableSanPham.getValueAt(select, 2)-sl;
//                        tableSanPham.setValueAt(slmoi, select, 2);
                        txtSoLuong.setText("");
                        tableSanPham.clearSelection();
                        btnThemGio.setEnabled(false);
                        txtGiaXuat.setText("");
                        txtMaSP.setText("");
                        txtTenSP.setText("");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Số lượng chỉ nhập số!");
            }

        }
    }//GEN-LAST:event_btnThemGioActionPerformed

    private void btnXoaphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaphieuActionPerformed
        if (tablePX.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn phiếu cần xóa");
        } else {
            int dongy = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (dongy == JOptionPane.YES_OPTION) {
                int id = (int) tablePX.getValueAt(tablePX.getSelectedRow(), 0);
                if (new PhieuXuatDAO().XoaPhieuXuatByID(id)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    showTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Xáo thất bại!");
                }

            }
        }
    }//GEN-LAST:event_btnXoaphieuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            int select = tableGiohang.getSelectedRow();
            listGioHang.remove(select);
            showGioHang(listGioHang);
            tinhTien();
            btnSua.setEnabled(false);
            btnXoa.setEnabled(false);
            resetTXT();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapHangActionPerformed
        if (tableGiohang.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Chưa thêm sản phẩm cần nhập!");
        } else {
            PhieuXuatKho px = new PhieuXuatKho();
            px.setMaPX(TangMaPX());
            px.setMaKH(getChonMaKH(boxKH.getSelectedIndex()));
            px.setMaNV(nhanvien.getMaNV());
            px.setTongTien(TongTien);
            int dongy = JOptionPane.showConfirmDialog(this, "bạn có chắc chắn muốn tạo phiếu?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (dongy == JOptionPane.YES_OPTION) {
                if (new PhieuXuatDAO().ThemPhieuXuat(px)) {
                    for (CTPhieuXuat ctpx : listGioHang) {
                        new CTPhieuXuatDAO().ThemCTPX(ctpx);
                        new SanPhamDAO().TruSoLuong(ctpx.getMaSP(), ctpx.getSoLuong());
                    }
                    JOptionPane.showMessageDialog(this, "Tạo thành công");
                    setDefault();
                } else {
                    JOptionPane.showMessageDialog(this, "Tạo thất bại!");
                }
            }
        }
    }//GEN-LAST:event_btnNhapHangActionPerformed

    private void boxLocKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLocKHActionPerformed
        filterPhieuNhap();
    }//GEN-LAST:event_boxLocKHActionPerformed

    private void boxLocNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxLocNVActionPerformed
        filterPhieuNhap();
    }//GEN-LAST:event_boxLocNVActionPerformed
    public void setDefault() {
        this.removeAll();
        this.add(pnPhieuXuat);
        this.repaint();
        this.revalidate();
        showTable();
    }

    public void resetTXT() {
        txtGiaXuat.setText("");
        txtMaSP.setText("");
        txtSoLuong.setText("");
        txtTenSP.setText("");
    }

    private void getSelectRowSP() {
        tableSanPham.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                listSP = new SanPhamDAO().getListSP();
                tableGiohang.clearSelection();
                btnSua.setEnabled(false);
                btnXoa.setEnabled(false);
                int SelectedRow = tableSanPham.getSelectedRow();
                if (SelectedRow == -1) {
                } else {
                    SanPham sp = listSP.get(SelectedRow);
                    txtMaSP.setText(sp.getMaSP() + "");
                    txtTenSP.setText(sp.getTenSP());
                    txtGiaXuat.setText(tien.format(sp.getGiaBan()) + "đ");
                    btnThemGio.setEnabled(true);
                    txtSoLuong.setText("");
                }
            }
        });
    }

    private void getSelectRowGH() {
        tableGiohang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int SelectedRow = tableGiohang.getSelectedRow();
                tableSanPham.clearSelection();
                btnThemGio.setEnabled(false);
                if (SelectedRow == -1) {
                } else {
                    CTPhieuXuat ctpx = listGioHang.get(SelectedRow);
                    txtMaSP.setText(ctpx.getMaSP() + "");
                    txtTenSP.setText(new SanPhamDAO().getSPbyID(ctpx.getMaSP()).getTenSP());
                    txtGiaXuat.setText(tien.format(ctpx.getGia()) + "đ");
                    txtSoLuong.setText(String.valueOf(ctpx.getSoLuong()));
                    btnSua.setEnabled(true);
                    btnXoa.setEnabled(true);
                }
            }
        });
    }

    private void showTableSP() {
        listSP = new SanPhamDAO().getListSP();
        DefaultTableModel model = (DefaultTableModel) tableSanPham.getModel();
        model.setRowCount(0);
        for (SanPham sp : listSP) {
            model.addRow(new Object[]{sp.getMaSP(), sp.getTenSP(),
                sp.getSoLuong()});
        }
    }

    private void showGioHang(ArrayList<CTPhieuXuat> list) {
        DefaultTableModel model = (DefaultTableModel) tableGiohang.getModel();
        model.setRowCount(0);
        STT = 0;
        TongTien = 0;
        for (CTPhieuXuat ctpx : list) {
            SanPham sp = new SanPhamDAO().getSPbyID(ctpx.getMaSP());
            Object[] giohang = {++STT, ctpx.getMaSP(), sp.getTenSP(), tien.format(ctpx.getGia()) + "đ", ctpx.getSoLuong()};
            model.addRow(giohang);
        }
    }

    private void showTable() {
        listPX = new PhieuXuatDAO().getListPhieuXuat();
        DefaultTableModel model = (DefaultTableModel) tablePX.getModel();
        model.setRowCount(0);
        for (PhieuXuatKho px : listPX) {
            NhanVien nv = new NhanVienDAO().getNhanVienByID(px.getMaNV());
            KhachHang kh = new KhachHangDAO().getKHbyID(px.getMaKH());
            model.addRow(new Object[]{px.getMaPX(), kh.getTenKH(), nv.getTenNV(), px.getThoiGian(), tien.format(px.getTongTien()) + "đ"});
        }
    }

    private void tinhTien() {
        if (listGioHang.size() == 0) {
            txtTongTien.setText("0đ");
            TongTien = 0;
        } else {
            for (CTPhieuXuat i : listGioHang) {
                TongTien += i.getGia() * i.getSoLuong();
            }
            txtTongTien.setText(tien.format(TongTien) + "đ");
        }
    }

    public void resetPanel() {
        STT = 0;
        DefaultTableModel model = (DefaultTableModel) tableGiohang.getModel();
        model.setRowCount(0);
        txtGiaXuat.setText("");
        txtMaPX.setText("");
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtSoLuong.setText("");
        txtTongTien.setText("0đ");
        btnThemGio.setEnabled(false);
        btnXoa.setEnabled(false);
        btnSua.setEnabled(false);
        tableGiohang.removeAll();
        tableSanPham.clearSelection();
        listGioHang.clear();
        TongTien = 0;
    }

    private int TangMaPX() {
        int mapx = 0;
        listPX = new PhieuXuatDAO().getAllPhieuXuat();
        if (listPX.size() == 0) {
            mapx = 1;
        } else {
            PhieuXuatKho pn = new PhieuXuatKho();
            pn = listPX.get(listPX.size() - 1);
            mapx = pn.getMaPX() + 1;
        }
        return mapx;
    }

    public void fillBoxKH() {
        listKH = new KhachHangDAO().getListKH();
        boxKH.removeAllItems();
        for (KhachHang kh : listKH) {
            boxKH.addItem(kh.getTenKH());
        }
    }

    public int getChonMaKH(int vt) {
        ArrayList<KhachHang> list = new KhachHangDAO().getListKH();
        KhachHang kh = list.get(vt);
        return kh.getMaKH();
    }

    private void filterPhieuNhap() {
        String khachHang = boxLocKH.getSelectedItem() != null
                ? boxLocKH.getSelectedItem().toString()
                : "Tất cả";
        String nhanVien = boxLocNV.getSelectedItem() != null
                ? boxLocNV.getSelectedItem().toString()
                : "Tất cả";

        DefaultTableModel model = (DefaultTableModel) tablePX.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        tablePX.setRowSorter(sorter);

        List<RowFilter<Object, Object>> filters = new ArrayList<>();

        if (!khachHang.equals("Tất cả")) {
            filters.add(RowFilter.regexFilter(Pattern.quote(khachHang), 1)); // cột 1: Nhà cung cấp
        }

        if (!nhanVien.equals("Tất cả")) {
            filters.add(RowFilter.regexFilter(Pattern.quote(nhanVien), 2)); // cột 2: Nhân viên nhập
        }

        if (filters.isEmpty()) {
            sorter.setRowFilter(null); // Không lọc gì cả
        } else {
            sorter.setRowFilter(RowFilter.andFilter(filters));
        }
    }

    private void fillBoxLoc() {
        listNV = new NhanVienDAO().getListNV();
        listKH = new KhachHangDAO().getListKH();
        boxLocKH.removeAllItems();
        boxLocNV.removeAllItems();
        boxLocKH.addItem("Tất cả");
        boxLocNV.addItem("Tất cả");
        for (NhanVien nv : listNV) {
            boxLocNV.addItem(nv.getTenNV());
        }
        for (KhachHang kh : listKH) {
            boxLocKH.addItem(kh.getTenKH());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxKH;
    private javax.swing.JComboBox<String> boxLocKH;
    private javax.swing.JComboBox<String> boxLocNV;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemGio;
    private javax.swing.JButton btnThemPhieu;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaphieu;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnChucNang;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLocPhieu;
    private javax.swing.JPanel pnPhieuXuat;
    private javax.swing.JPanel pnRight;
    private javax.swing.JPanel pnThemPhieuXuat;
    private javax.swing.JTable tableGiohang;
    private javax.swing.JTable tablePX;
    private javax.swing.JTable tableSanPham;
    private javax.swing.JTextField txtGiaXuat;
    private javax.swing.JTextField txtMaPX;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNVXuat;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
